version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.0.0

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
        environment:
          DJANGO_SECRET_KEY: test_django_secret_key
          DJANGO_DEBUG: False
          DJANGO_ALLOWED_HOSTS: localhost
          DJANGO_DB_NAME: waracle_tech_test
          DJANGO_DB_USER: postgres
          DJANGO_DB_PASSWORD: postgres
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: waracle_tech_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/development.txt
      - run:
          name: Run tests
          command: |
            pytest --cov=. --cov-report=xml --ds=waracle_tech_test.settings.development
      - run:
          name: Ruff
          command: |
            ruff check .
      - codecov/upload