# Generated by Django 4.2.7 on 2023-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="image_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cake",
            name="yum_factor",
            field=models.IntegerField(),
        ),
    ]
